apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
        tier: backend
    spec:
      containers:
      - name: my-pod
        image: docker.io/dilly97/mypod:v1.0-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
spec:
  selector:
    app: my-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
