### This is for REST API Testing
### Click Send Request

###
GET http://127.0.0.1:8080/hello HTTP/1.1
content-type: application/json

{
    "info": { 
        "name": "andy", 
        "age": 33 
    }, 
    "hobby": ["sports", "coding"]
}